parallel-jobs = 1
compression-level = 9

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
build-mode = "both"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'GmsCore support'"
